root: true

env:
    browser: true

parser:
    babel-eslint

plugins:
    - babel
    - jest
    - module-resolver
    - react-hooks

extends:
    - "plugin:jest/recommended"

parserOptions:
    sourceType: "module"

rules:
    #
    # Plugin: babel
    #

    babel/semi: 1



    #
    # Plugin: jsx-a11y
    #

    # Rule: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md
    jsx-a11y/anchor-is-valid:
        - error
        -
            components:
                - Link
            specialLink:
                - to
                - hrefLeft
                - hrefRight
            aspects:
                - noHref
                - invalidHref
                - preferButton
    jsx-a11y/label-has-for: off

    jsx-a11y/label-has-associated-control:
        - off

    #
    # Plugin: react
    #

    # Rule: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-typos.md
    # This rule is disabled because it's causing a bug when running eslint
    # react/no-typos:
    #     - off

    # Rule: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md
    # This rule is disabled because it's causing a bug when running eslint
    react/jsx-filename-extension:
        - 1
        - extensions:
                - .js

    import/no-internal-modules:
        - 1

    object-curly-newline:
        - 1
        - consistent: true

    react/destructuring-assignment:
        - off

    react/jsx-one-expression-per-line:
        - 0

    import/no-unresolved: [
        2,
    ]

    react-hooks/rules-of-hooks:
        - error
    react-hooks/exhaustive-deps:
        - error
